name: cuet_event_management
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0-417.1.beta <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  image_picker:
  dotted_border:
  video_thumbnail:  
  path_provider: 
  pdf: 
  syncfusion_flutter_pdf: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/OpenSans-Regular.ttf
